모두의 연구소, 2024 AI 코칭스터디 팀 활동 과정에서 실습했던 내용과 추가 리서치했던 코드를 정리한 내용입니다. 
- @엔터6(변찬우) 

# **ndarray**

- NumPy의 N차원 배열 객체
  - numpy는 np.array 함수를 활용하여 '배열'을 생성함
- Python의 list와 가장 큰 차이점은, 하나의 데이터 타입만 넣을 수 있다
  - Python List는 Dynamic typing을 지원 : ref 주소만 가리킴(*but 속도가 오래걸림)
  - 하지만, ndarray는 지원하지 않는다
    - numpy는 하나의 데이터 type만 배열에 넣을 수 있음
    - C의 Array를 사용하여 배열을 생성함


0. 넘파이 패키지 추가하기 

In [6]:
import numpy as np

1. 배열 생성
  - a의 list를 int 타입의 ndarray로 생성하여 a_ndarray 변수에 담는다.

In [7]:
a = [1, 2, 3, 4, 5]
a_ndarray = np.array(a, int)
print(a_ndarray)

type(a_ndarray[3])  # 타입 확인

[1 2 3 4 5]


numpy.int64

2. int 타입의 ndarray 생성하기
  - np.array 함수는 기존의 리스트 형태의 데이터와 데이터 타입을 입력받아 ndarray 형태로 변환해주는 함수이다.

In [8]:
test = [1, 4, 5, 8]
test_array = np.array(test, float)
print(test_array)

type(test_array[3]) # 타입 확인

[1. 4. 5. 8.]


numpy.float64

 3. String 타입의 자동 형 변환
  - numpy는 하나의 데이터 type만 배열에 넣을 수 있음
  - List에 여러 데이터 타입이 존재하더라도 ndarray는 알아서 하나의 타입으로 형 변환을 수행

In [9]:
b = [1, 4, 5, '8']
b_ndarray = np.array(b, float)
print(b_ndarray)  # 출력을 해서 확인할 수도 있고

type(b_ndarray[3])  # 타입 확인, 'float로 변환'된 것을 확인할 수 있다.

[1. 4. 5. 8.]


numpy.float64

4. shape과 dtype property 사용하는 방법

  - 1 차원

In [10]:
a = [1, 2, 5, 8]  # 4, 1차원 배열 선언
a_ndarray = np.array(a, int)
print("shape : ", a_ndarray.shape) # 1rd order tensor
print("ndim : ", a_ndarray.ndim) # number of dimensions
print("size : ", a_ndarray.size) # 4 == 4
print("dtype : ", a_ndarray.dtype) # int64출력

shape :  (4,)
ndim :  1
size :  4
dtype :  int64


 - 2 차원

In [11]:
c = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]  # 4x3 2차원 배열 선언
c_ndarray = np.array(c, int)
print("shape : ", c_ndarray.shape) # 2rd order tensor
print("ndim : ", c_ndarray.ndim) # number of dimensions
print("size : ", c_ndarray.size) # 12 == 4x3
print("dtype : ", c_ndarray.dtype) # int64출력

shape :  (3, 4)
ndim :  2
size :  12
dtype :  int64


  - 3 차원

In [12]:
d = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
     [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
     [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
     [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]  # 4x3x4 3차원 배열 선언
d_ndarray = np.array(d, int)
print("shape : ", d_ndarray.shape) # 3rd order tensor
print("ndim : ", d_ndarray.ndim) # number of dimensions
print("size : ", d_ndarray.size) # 48 == 4x3x4
print("dtype : ", d_ndarray.dtype) # int64출력

shape :  (4, 3, 4)
ndim :  3
size :  48
dtype :  int64


5. 데이터 타입 변경
  - 위와 같은 예제도 데이터가 많아서 복잡한데, 실제 데이터 분석을 위해 사용되는 데이터는 훨씬 방대하다.
  - 그렇기 때문에 데이터의 상/하한 값을 안다면, 그에 맞춰 dtype을 np.int8 또는 float32와 같이 줄여서 메모리 낭비를 줄일 수 있다.

In [13]:
d_ndarray = np.array(d, dtype=np.int8) # 기본은 int32인데, 메모리 낭비가 커서 int8로 사용가능
print("dtype : ", d_ndarray.dtype) # int8출력

addtxt_array = np.array(b, np.float32)
print("dtype : ", addtxt_array.dtype) # int8출력

dtype :  int8
dtype :  float32


6. nbytes로 데이터의 Byte 크기 추출하기
  - Machine Learning을 하며 Y값을 잘 예측하기 위해서는 float를 사용하여 소수점까지 정확하게 계산할 필요가 있다.
  - 그래서 주로 float를 사용할 것이고, 이런 데이터의 Byte 단위 크기를 알고 싶다면 .nbytes를 사용하면 된다.

In [14]:
# 소수점까지 있어야 정확한 Y값 예측이 가능해져서 대부분의 경우 float를 사용함
d_ndarray = np.array(d, dtype=np.float32)
print(d_ndarray.nbytes) # byte size를 출력함. 48개 x 4B == 192B 출력

192


**마무리**

- ndarray는 NumPy에서 N차원 배열을 사용할 때 사용되는 기본이다.
- 즉, 데이터 분석을 하기 위해서는 ndarray를 늘 사용한다고 이해하면 좋다.
- np.array 함수를 통해서 ndarray로 변환하고, 이때 기본 list 데이터와 원하는 데이터 타입을 지정할 수 있다.
- shape/dtype/ndim/size/nbytes 등의 property를 사용하여 데이터에 대한 정보를 얻을 수 있다.

# **Reshape**

1. 기본 데이터를 ndarray로 입력하고, .shape을 통해 기대한 값이 나오는지 확인
  - 지난 포스트에 정리한 np.array와 .shape을 통해서 기본 데이터가 잘 들어갔는지 확인한다.
  - 생각보다 데이터 입력부터 틀려서 원하는 결과가 나오지 않는 경우도 많으니, 꼭 확인 후에 넘어가는 것이 정신건강에 이롭다.

In [15]:
import numpy as np

test_matrix = [[1, 2, 3, 4],
               [5, 6, 7, 8]] # 2x4 데이터 배열 선언
test_array = np.array(test_matrix)
test_array.shape # 기존의 2x4 확인

(2, 4)

2. .reshape함수를 사용하여 각종 형태로 변환
  - .reshape은 말 그대로 array의 크기를 바꿔주는 함수이다.
  - '변환되는 array의 크기(element의 개수)가 같다'는 원칙만 지켜지면, 모든 reshape이 가능하다

In [16]:
test_array.reshape(4, 2)  # 4x2로 변환 가능

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
test_array.reshape(2, 2, 2)  # 총 element 수만 동일하다면, 어떻게든 변환 가능

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
test_array.reshape(8,)  # (8,) Tuple로 reshape

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
test_array.reshape(2, 4).shape  # 이렇게 데이터를 변형한 뒤에 다시 shape를 봐도 2x4로 잘 보임

(2, 4)

3. -1 index와 flatten 함수
  - -1을 쓰면, row에 맞춰서 column 개수를 맞춰달라는 것으로 해석하여 알아서 4를 사용한다(반대로 .reshape(-1, 2)를 하면 4x2의 배열로 reshape 한다)
  - .flatten 함수는 test array를 하나의 row로 변환한다.(1차원으로 변환)

In [20]:
test_array.reshape(2, -1)  # 2개의 row에 맞춰서 column 수는 "알아서 맞춰줌"

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
test_array.reshape(-1, 8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [22]:
test_array.flatten()  # .reshape(1,-1)과 동일하게 동작해서 한 row로 변환함

array([1, 2, 3, 4, 5, 6, 7, 8])

마무리
  - ndarray의 형태를 바꿔야 하는 경우는 생각보다 많다.
  - 주로 다른 데이터와 통합하여 관리하기 위해서는 형태를 바꿔야 하는데,
  - 이때 사용되는 함수가 .reshape이다
  - 기본 원칙은 '개체 수가 동일하면 reshape은 가능하다'라는 것이다.
  - -1 index은 자동으로 숫자를 맞춰주고 flatten 함수는 1차원으로 변환시켜준다

# **Indexing & Slicing**

1. 인덱싱 : test_array[1, 2]
    - 0-base indexing이기 때문에 첫 줄은 0번 줄이다
    - 가로-세로순,
    - 0과 1(오른쪽으로 2칸), 1과 2(아래로 2칸) = 예제 기준으로는 3

In [7]:
import numpy as np

test_list = [[1, 2, 5, 8],
             [2, 3, 6, 9],
             [3, 4, 7, 10],
             [4, 5, 8, 11]] # 4 x 4 array
test_array = np.array(test_list, int)

print(test_array[1][2]) # 6 출력, # 0-base indexing이기 때문에 첫 줄은 0번 줄이다
print(test_array[1, 2]) # 동일하게 6 출력

6
6


2. 슬라이싱 : ndarray 배열 참조 규칙
    - 배열 한 칸의 내부는 최대 3개 조건으로 설정할 수 있는 'Start(이상):End(미만):Interval'의 parameter를 사용
    - ':k' = k 미만, 'k:' = k 이상
    - 'k:j' = k 이상 & j 미만
    - ' : ' = 모든
    - ' ::k'= 전부 k칸씩 띄어서
    - 'k::j'= k부터 & 전부 k칸씩 띄어서
    - 'k:j:i'= k부터 & j미만까지, k칸씩 띄어서

- Slicing 예제 #1
    - Slicing이란 배열 중에서 원하는 부분만 뽑아 쓰기 위해 '잘라서 사용하는' 기능이다.
    - 위의 예제를 보면, 행의 위치에 1:2라는 것은 1이상 & 2 미만을 뜻한다.
    - 행 위치에 있으니 1 이상 2 미만의 행을 의미하는 것이고, 같은 값이 콤마 뒤에 있었다면 1 이상 2 미만의 열이 되었을 것이다.
    - 예제의 열 위치에 있는 :2는 2미만을 뜻한다. 즉, 2 미만의 모든 열을 slice 하라는 의미이다.
    - test_array[1:2, :2]는 '2차원 배열'인 [[2,3]] 값을 반환하게 된다.

In [8]:
test_array[1:2, :2] # 1번행 이상 / 2번행 미만, 2번 열 미만 출력 -> "2차원으로 출력

array([[2, 3]])

- Slicing 예제 #2
    - 행은 1번 행을 읽어온다.
    - 열은 2 미만의 열을 읽어온다.
    - 그렇기 때문에 데이터는 [2, 3]이 반환되어 1번 예제와 동일한 결과물 같아 보이지만,
    - 2번 예제는 '1차원 배열'을 반환한다.

In [9]:
test_array[1, :2] # 동일하게 출력되지만, -> "1차원으로 출력

array([2, 3])

- Slicing 예제 #3
    - 행에 세미콜론(:)만 있는 것은 '모든 행'을 뜻한다.
    - 열의 2:는 2 이상의 모든 열을 뜻한다.
    - 합치면 모든 행의 2열 이상의 데이터를 가져오라 는 의미가 된다.

In [10]:
test_array[:, 2:] # 모든 행, 2번 열 이후 출력

array([[ 5,  8],
       [ 6,  9],
       [ 7, 10],
       [ 8, 11]])

-   Slicing 예제 #4
    - 모든 행의 데이터를 출력
    - 모든 열을 출력하되, 짝수번째 열들만 출력

In [11]:
test_array[:, ::2] # 모든 행 + 모든 열을 2칸씩 띄워서

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

-   Slicing 예제 #5
    - 'Start:End:Interval'의 문법을 사용한다.
    - 그리고 아무런 값이 없을 경우의 Default 값은 Start = 0, End = Total Row/Col count, Interval = 1이다.
    - 행의 1::2는 1번부터 시작해서, 끝까지 출력하되, 2 행씩 건너뛰어서 출력하라는 것이다. (1번, 3번 행 출력)
    - 열의 0:4:3은 0번 열부터 시작해서, 4번 열 미만까지 출력하되, 3열씩 건너뛰어서 출력하라는 것이다. (0번, 3번 열 출력)

In [12]:
test_array[1::2, 0:4:3] # 1번 행부터 끝까지, 2행씩 띄워서 출력
                        # 0번 열부터 4번 미만 열까지, 3열씩 띄워서 출력

array([[ 2,  9],
       [ 4, 11]])

마무리

- Indexing은 비교적 단순하다. 각 dimension 별로 값을 주면, 해당 위치의 값을 반환해주는 것이 전부다.
- Slicing은 생각보다 간단하지 않지만, 원리만 이해하고 나면 쉽게 적용이 된다.
    - Start:End:Interval의 문법으로 Slice 할 위치를 지정한다.
    - 각 위치의 default 값은 0:Total count:1이다.
- 그래서 Start index를 생략하면 처음부터 전부라는 의미이고
- End Index를 생략하면 끝까지 전부라는 의미이고
- Interval을 생략하면 건너뛰지 않고 전부라는 의미이다.

-------------------------------------

출처: [ndarray 이해하기](https://coding-grandpa.tistory.com/24)

# **Creation Function**

생성 함수
- 말 그대로 무언가를 만드는 함수들을 통칭하는 용어이다.
- NumPy는 array를 쉽게 만들기 위한 (내장)함수( :arange, zeros, empty..)들을 제공하고 있다.

1. arange 함수
  - arange는 3개의 Parameter를 입력받는다 : Start, End, Interval.
  - Start 이상, End 미만의 값을 Interval 간격으로 생성하여 하나의 배열에 담아주는 함수이다.
  - Parameter를 2개만 전달할 경우 Start와 End로 인식하여 동작한다 (Interval의 Default 값은 1이다).
  - Parameter를 1개만 전달할 경우 End로 인식하여 동작한다 (Start의 Default 값은 0이다).
  - 이렇게 arange를 통해 만들어진 배열을 .reshape 함수를 통해서 원하는 형태로 변형하여 사용할 수도 있다.

In [29]:
import numpy as np

np.arange(0, 5, 0.5) # 0이상 5미만까지 0.5씩 증가하는 값의 array를 만들어라

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [30]:
np.arange(30) # 0이상 30미만까지 1씩 증가하는 값의 array를 만들어라

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
np.arange(30).reshape(5,6) #array를 np matrix로 변형하여 사용할 수 있다.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

2. zeros 함수
  - zeros 함수는 shape와 dtype을 전달받아서 동작하는 함수이다.
  - shape를 통해서 크기를 지정해주고, dtype으로 data type을 지정해준다.
  - 그러면 shape와 dtype에 해당하는 0으로 채워진 배열을 반환해주는 함수이다.

In [32]:
np.zeros(shape=(10,),   # (10,) tuple 형태로 크기 지정
         dtype=np.int8) # 0으로 만들어줌

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

3. empty 함수
  - zeros 함수와 동일한 parameter를 입력받는 함수이다.
많이들 zeros와 헷갈리는 함수인데, zeros와 empty의 차이는 초기화 여부이다.
  - zeros는 메모리를 할당받아 0으로 초기화한 뒤에 반환하지만, empty는 메모리 할당만 받고 '초기화 없이 반환'한다.
그렇기 때문에 empty 함수를 '실행할 때마다 값이 다른 것을 확인'할 수 있다.
  - 이는 해당 메모리 영역에 '어떤 데이터가 남아있었던지 상관없이 그대로 영역의 주소만 알려줄 뿐', 초기화는 사용자에게 맡기기 때문이다.
  - empty의 장점은 초기화를 생략하기 때문에 성능이 조금 더 개선된다는 점인데, ***실무에서는 거의 사용되는 적이 없다. ***

In [33]:
np.empty(shape=(10,),   # (10,) tuple 형태로 크기 전달
         dtype=np.int8) # dtype 지정

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

(중간 점검 1)

  - arange 함수 : start/end/interval을 입력받아서 배열을 만들어준다.
  - arange 함수 뒤에 .reshape을 사용해서 크기를 조절하여 사용하는 경우가 많다.
  - zeros 함수 : shape과 dtype을 입력받아 0으로 초기화된 배열을 만들어준다.
  - empty 함수 : shape과 dtype을 입력 받아 초기화되지 않은 배열을 만들어준다.

4. ones_like 함수
  - ones_like 함수는 'matrix나 vector'를 parameter로 전달받는다.
  - 전달받은 matrix/vector와 '동일한 크기'의 matrix/vector를 생성하여 '1로 초기화'하여 반환하는 함수이다.
  - dtype을 지정해주면 원하는 data type의 배열로 생성해서 반환한다

In [34]:
test_matrix = np.arange(30).reshape(5,-1) # 샘플용 매트릭스
test_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
np.ones_like(test_matrix, np.float32) # 원본과 동일한 크기로 만들어짐

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

5. Zeros_like 함수
  - 이름에서 유추할 수 있듯, ones_like과 완전히 동일하다.
  - 유일한 차이점은 1로 초기화하지 않고 0으로 초기화한다는 점만 다르다.

In [36]:
np.zeros_like(test_matrix, np.int8) # 1 대신 0으로 구성

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

6. empty_like 함수
  - empty_like도 동일하다.
  - 유일한 차이점은 초기화 없이 메모리 할당만 받아서 전달한다는 것이다.

In [37]:
np.empty_like(test_matrix, np.int32)

array([[1065353216, 1065353216, 1065353216, 1065353216, 1065353216,
        1065353216],
       [1065353216, 1065353216, 1065353216, 1065353216, 1065353216,
        1065353216],
       [1065353216, 1065353216, 1065353216, 1065353216, 1065353216,
        1065353216],
       [1065353216, 1065353216, 1065353216, 1065353216, 1065353216,
        1065353216],
       [1065353216, 1065353216, 1065353216, 1065353216, 1065353216,
        1065353216]], dtype=int32)

(중간 점검 2)
  - ones_like, zeros_like, empty_like는 따로 shape을 지정해주지 않고, 기존 matrix/vector를 전달할 수 있어서 편리하다.

  7. Identity 행렬 만들기
    - Identity matrix란 *항등 행렬 혹은 단위 행렬* 이라고 불린다..
쉽게 말해 '**가운데 대각선의 값**'이 전부 1이고, 나머지는 0으로 채워진 행렬을 뜻한다.
    - 숫자들 간의 곱셈을 할 때 어떤 수를 1과 곱해도 원래의 숫자가 나오듯,
      - Identity matrix는 어떤 행렬을 곱해도 원래의 행렬이 나오는 행렬을 의미한다.
      - 그래서 identity matrix라는 이름을 붙였는데, 오히려 항등 행렬/단위행렬이란 이름은 직관적이지 못하다고 생각한다.
    - n은 row/col의 개수로 전달하고, dtype으로 데이터 타입을 지정해주면, n x n의 identity 행렬이 생성된다.

In [38]:
#identity 행렬 만들기 (대각 행렬, 대각선이 1인 행렬)
np.identity(n=5, dtype=np.int8) # 5x5의 np.int8의 identity 행렬 생성

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

8. np.eye 함수
  - eye 함수로 생성되는 배열은 identity와 유사하다.
  - 차이는 Identity 행렬은 항상 nxn의 행렬이라면, eye는 원하는 NxM으로 행렬을 만들 수 있다.
  - k 변수를 통해서 identity matrix가 시작할 열을 지정해줄 수 있다.
  - 위의 예제에서 보면, N=3/M=5/k=1이기 때문에3x5 행렬을 만들고, 1번 열부터 시작하여 1을 대각선으로 입력하고, 나머지는 0으로 채워진 행렬을 array 형태로 반환한다.

In [39]:
np.eye(N=3, M=5,      # 총 행렬의 크기는 3x5 로 만들어 달라
            k=1,      # identity matrix의 시작은 1열부터 시작하라
			 dtype=np.int8) # dtype은 int8로 설정

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

9. np.daig 함수
  - diag 함수는 parameter로 전달받은 행렬의 k번째 열부터 있는 대각선의 값들을 1차원 array로 반환하는 함수이다.
  - np.diag(matrix, k=1)은 'matrix 행렬의 1번 열부터의 대각선 값들을 반환해줘' 라는 요청이 된다.
  - 그렇기 때문에 [0, 1], [1, 2]에 있는 값들을 뽑아서 하나의 배열로 반환한다.
  - 그래서 Out[4]는 [1, 5]의 값을 반환하게 된다.

In [40]:
matrix = np.arange(9).reshape(3,-1)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
np.diag(matrix, k=1) #matrix의 k열을 기준으로 대각선에 있는 값들을 array에 담아서 반환함

array([1, 5])

(중간 점검 3)
- Identity 행렬은 행렬의 계산에 항상 필요하기 때문에, 어떤 parameter로 동작하는지 기억해두자.
- eye와 diag 함수도 때에 따라 요긴하게 쓰이는 상황들이 생긴다. 저걸 직접 구현하려면 노력 대비 너무 단순한 기능이기 때문에, 주어진 함수를 잘 사용해서 더 의미 있는 알고리즘을 짜는데 시간을 투자하자.

10. 2차원 배열에서 sum 함수 사용하기

In [42]:
import numpy as np
test_array = np.arange(1,13).reshape(3,4) # 1~12까지의 값을 갖는 test_array를 생성한다.
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
test_array.sum() #  배열의 전체 요소들의 합을 반환

78

11. 차원별 sum 구하기

In [44]:
test_array.sum(axis=0) # 각 col 행의 합으로 하나의 row 열 구성 = [c-sum,c-sum,c-sum,c-sum]  

array([15, 18, 21, 24])

In [45]:
test_array.sum(axis=1) # 각 row 열의 합으로 하나의 col 행을 구성 = [r-sum,r-sum,r-sum]  

array([10, 26, 42])

12. 3차원에서의 차원 이해하기 (shape 이해하기)

In [46]:
third_order_tensor = np.array([test_array, test_array, test_array]) 
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

3x4 array를 3개 붙이면
- 새로운 차원이 제일 앞에 추가되고 총개수는 3개가 된다 
- 그래서 첫 axis에 3이 추가된다.
- 새로 추가되는 axis가 axis=0이 되고, 기존의 0,1 axis는 각각 1,2 axis로 밀려나게 된다.
- 이와 같이 각 차원이 몇번째 axis인지를 볼 수 있어야 한다

In [47]:
third_order_tensor.shape

(3, 3, 4)

13. Mathematical functions 수학 연산자 함수 
    - 변형된 axis로 차원별 sum, mean, std(표준편차) 계산하기
    - 그 외 다양한 연산자
        - exponential: exp, expml, exp2, log, 10g10, loglp, 10g2, power, sqrt
        - trigonometric: sin, cos, tan, acsin, arccos, atctan 
        - hyperbolic: sinh, cosh, tanh, acsinh, arccosh, atctanh 

axis=0인 경우, 새로 추가된 제일 높은 차원들끼리 더하는 것이다. 
    -  즉, test_array들끼리 더해달라는 것이 되기 때문에 sum(axis=0)의 결과값은 기존 test_array의 각각의 값에 3을 곱한 것과 동일하다 (3 = 1+1+1, 6 = 2+2+2 등)

In [48]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

axis=1인 경우는 test_array의 axis=0과 동일하기 때문에, test_array의 행들끼리 더하라는 의미이다. 그렇기 때문에 15 = 1+5+9, 18 = 2+6+10, 21 = 3+7+11 등의 순서로 결과값이 나온다.

In [49]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

axis=2인 경우는 test_array의 axis=1과 동일하기 때문에, test_array의 열들끼리 더하라는 의미이다. 그렇기 때문에 10 = 1+2+3+4, 26=5+6+7+8, 42=9+10+11+12 등의 결과값이 나오게 된다.

In [50]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [51]:
third_order_tensor.mean(axis=2)

array([[ 2.5,  6.5, 10.5],
       [ 2.5,  6.5, 10.5],
       [ 2.5,  6.5, 10.5]])

In [52]:
third_order_tensor.std(axis=2)

array([[1.11803399, 1.11803399, 1.11803399],
       [1.11803399, 1.11803399, 1.11803399],
       [1.11803399, 1.11803399, 1.11803399]])

마무리
- 배열 계산을 할 경우 차원을 이해하는 것은 정말 중요하다.
- 새로 추가되는 차원은 앞의 index로 추가된다는 기본 규칙을 이해하는 것이 중요하다.
- 그런 차원들중에서 각각 합을 구하고 싶으면 axis parameter를 통해서 전달할 수 있다.
- 내가 의도한 코드를 잘 짜는 것도 중요하지만, 다른 사람이 짠 코드의 의도를 정확하게 이해하기 
    - 위해서는 배열의 차원을 이해하고, 차원별로 합/평균/표준편차를 구했을 때 어떤 의미인지 이해하는 것이 매우 중요하다.

# **random sampling 함수** 

1. np.random.uniform, 균등 분포 정보를 생성하여 array에 만들기

In [15]:
np.random.uniform(0,1,1000) # [균등 분포 Parameter] 최소 0, 최대 1, 개수 1000개

array([0.89943302, 0.25134183, 0.31769065, 0.32529121, 0.52262105,
       0.77911074, 0.88340608, 0.49678297, 0.90235298, 0.06667087,
       0.61596349, 0.90074438, 0.51445868, 0.65704727, 0.53128098,
       0.13151622, 0.14285406, 0.79341152, 0.1012568 , 0.21997143,
       0.75581849, 0.60525128, 0.63766362, 0.84198714, 0.23606937,
       0.2188299 , 0.19213914, 0.35850438, 0.66987183, 0.56201678,
       0.22588746, 0.45643369, 0.94567916, 0.36225458, 0.25309986,
       0.54858477, 0.06185472, 0.64494731, 0.35804031, 0.690393  ,
       0.89723323, 0.29203183, 0.27931551, 0.14229641, 0.72882015,
       0.12801964, 0.49465631, 0.89552835, 0.81200799, 0.89853471,
       0.8664579 , 0.96983906, 0.35169284, 0.68127336, 0.84249714,
       0.06378663, 0.61740659, 0.06554155, 0.44338583, 0.73530711,
       0.34495145, 0.44227884, 0.5282908 , 0.29293849, 0.12841884,
       0.15483031, 0.97477802, 0.837102  , 0.36116674, 0.00826994,
       0.17827848, 0.40689908, 0.37735868, 0.6618889 , 0.61557

2. np.random.normal, 정규분포

In [16]:
np.random.normal(0,1,1000) # [정규분포] 평균 0, 표준편차 1, 개수 1000개

array([-1.88783355e+00, -9.99009544e-01, -1.32918820e+00, -1.29662724e+00,
        5.68474257e-01, -1.63254185e+00,  1.04708089e+00,  2.56234847e-01,
       -4.06108347e-01, -4.58009368e-01,  6.29352354e-01,  5.89257073e-01,
        1.59320674e+00,  1.18542697e-01, -6.82042231e-01, -6.10660524e-01,
        1.17761252e+00, -5.27698478e-01, -1.85995485e-01, -2.46867125e-01,
        2.09504606e-01, -9.93570912e-01,  1.00278610e+00, -7.77986427e-01,
       -1.10761031e+00, -1.73071906e+00, -4.46601308e-01, -6.42216049e-01,
        1.77695579e+00, -1.57063339e+00,  7.77579717e-01, -6.80612147e-01,
       -1.14914680e+00,  3.20152641e-01, -3.81693613e-01, -3.30487074e-01,
       -1.51986932e+00, -1.77122711e+00,  1.44118057e+00, -1.21744111e+00,
        2.83655599e+00,  3.80170186e-01,  2.87439134e-01, -2.47978749e+00,
       -1.44573425e+00, -1.56491708e-02, -4.36498935e-01,  8.35779604e-01,
        6.44253442e-01, -1.08521134e+00,  1.28360673e+00,  1.07542977e+00,
        3.14706210e-02, -

# **Array 붙이기**

1. hstack과 vstack 함수
    - vstack/hstack과 concatenate 함수를 통해서 두 개 이상의 '백터 array(배열)'을 하나로 합칠 수 있다

In [53]:
a = np.arange(1,4) 
a

array([1, 2, 3])

In [54]:
b = np.arange(4,7) 
b

array([4, 5, 6])

- horizontal stack, 두 개의 배열을 좌우로 붙여주는 함수 - 때문에 row의 개수는 '동일'해야 한다

In [55]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

- vertical stack,  두 개의 배열을 위아래로 붙여주는 함수 - 붙여야하기 때문에 col의 개수는 동일해야 한다

In [56]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

2. np.concatenate 함수

In [57]:
c = np.array([[1, 2], [3, 4]]) 
d = np.array([[5], [6]]) 
c, d

(array([[1, 2],
        [3, 4]]),
 array([[5],
        [6]]))

In [60]:
np.concatenate((c,d), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [71]:
e = np.array([[1, 2], [3, 4]]) 
f = np.array([5, 6]) # shape == (2,) 
e, f

(array([[1, 2],
        [3, 4]]),
 array([5, 6]))

In [69]:
e.shape

(2, 2)

In [72]:
f.shape

(2,)

e에 f를 (axis=1)로 병합하기 위해 shape을 맞추는 과정
- hstack과 vstack와 마찬가지로 concatenate 또한 추가를 위해서는 row/col의 개수 맞추어야 한다
- 만약 axis=0으로 concatenate을 할 경우에는 행을 추가해야 한다

In [62]:
f = f[np.newaxis,:] # 차원을 추가한다 
f # shape == (1,2)  # 새로운 차원이 앞으로!, 기존 차원은 뒤로 이동!!

array([[5, 6]])

In [63]:
f.T.shape # shape == (2,1)

(2, 1)

In [66]:
f.T 

array([[5],
       [6]])

In [64]:
np.concatenate((e,f.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

# **b/t arrays** 

1. Array와 Array 간의 사칙 연산 
    - 같은 크기의 array 간 연산을 하면 행렬의 연산과 동일하게 각 요소들 간의 연산이 수행된다. 

In [17]:
import numpy as np
test_a = np.array([[1,2,3], [4,5,6]], float) 
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [19]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

2. ndarray 곱과 피보팅 : Dot Product(스칼라곱-내적)와 Transpose(전치 행렬 매트릭스)

In [20]:
test_a = np.arange(1,7).reshape(2,3) 
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
test_b = np.arange(7,13).reshape(3,2) 
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

- Dot Product : 선형대수학에서 스칼라곱 또는 점곱은 유클리드 공간의 두 벡터로부터 실수 스칼라를 얻는 연산이다. 
    - 스칼라곱이 유클리드 공간의 내적을 이루므로, 이를 단순히 '내적'이라고 부르기도 한다. 
    - 스칼라곱의 개념의 물리학 배경은 주어진 힘이 주어진 변위의 물체에 가한 일을 구하는 문제이다. 
    - 유클리드 공간의 두 벡터로부터 실수 스칼라를 얻는 연산이다.

In [22]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

- Transposed matrix : 선형대수학에서 전치 행렬은 행과 열을 교환하여 얻는 행렬이다. 
    - 주대각선을 축으로 하는 반사 대칭을 가하여 얻는 행렬이다.
    - .transpose 혹은 .T 연산자를 사용해서 행렬을 transpose 할 수 있다.

In [23]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

- test_a를 Transpose 한 결과값에 test_a함수 곱하기 

In [25]:
test_a.transpose().dot(test_a) # test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

3. Array와 Scalar 간의 연산
    - array와 scalar를 더하면 각 요소에 scalar를 더한 것과 동일한 연산을 수행한다.
    - 3이라는 scalar 값이 [[3., 3., 3.], [3., 3., 3.]] 배열로 확장되어 연산된다.
    - 이러한 동작을 broadcasting이라고 한다.
    - broadcasting의 정의는 '같은 shape으로 복사/확장'이다.

- 용어 비교
    - 스칼라 (수학): 벡터 공간에서 벡터를 곱할 수 있는 양
    - 스칼라 (물리): 특정 좌표계와 관련이 없는 양 
    - 변수 (컴퓨터 과학): 한번에 하나의 값만 보유할 수 있는 원자량.

In [26]:
test_c = np.array([[1,2,3], [4,5,6]], float) 
test_c

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
scalar = 3

In [28]:
test_c + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [29]:
test_c + 4

array([[ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

4. Array와 vector 간의 연산
    - vector와의 연산에서도 동일하게 broadcasting이 일어난다.
    - 수식으로 보면 4x3 matrix + 1x3 vector를 더하는 것 같지만,
    - 실제 연산 시에는 
        - 1x3 vector가 4x3 matrix로 broadcasting 되어 
            ```
            ([      
                [10,20,30], 
                [10,20,30], 
                [10,20,30], 
                [10,20,30]
                            ])`
        - test_d matrix와 합쳐지기 때문에 
        - Out[16]과 같은 결과가 나온다.

In [30]:
test_d = np.arange(1,13).reshape(4,3) 
test_d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
vector = np.arange(10, 40, 10) 
vector

array([10, 20, 30])

In [32]:
test_d + vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

5. Vector와 vector 간의 연산
    - 다른 vector 간의 연산은, 양쪽 다 broadcasting이 일어난 뒤에 연산이 수행된다.
    - 풀이
        1) 첫 vector는 
            ```
            [
                [10,20,30], 
                [10,20,30], 
                [10,20,30]] 로 broadcasting이 되고
        2) 둘째 vector는 
            ```
            [
                [10,10,10], 
                [20,20,20], 
                [30,30,30]]로 broadcasting이 된다.
        3) Broadcasting이 된 이후의 연산은 각 요소별로 이루어지기 때문에, 
        4) Out[18]과 같은 결과가 나오게 된다.

In [34]:
vector_transpose = vector.reshape(-1,3).T 
vector_transpose

array([[10],
       [20],
       [30]])

In [35]:
vector + vector_transpose

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])

6. 마무리
    - 같은 크기의 Array 간의 연산은 각 요소별로 이루어진다.
    - 크기가 다른 Scalar나 Vector를 Array와 연산하기 위해서는 
        - Scalar/Vector를 Array와 같은 크기로 확장시켜주는 동작이 선행되는데, 
        - 이를 Broadcasting이라고 한다.
    - 즉 Array + Scalar 혹은 Array + Vector를 수행하면 
        - Scalar/Vector를 Array로 확장을 시킨 뒤에 
        - 각 요소별로 연산을 수행하게 된다.

# **비교 연산자와 논리 연산자**

- 일반 scalar 값의 대소 비교를 하듯 Array에도 대소 비교가 필요하다. 
- NumPy에는 대소비교 뿐만 아니라, 논리 연산 (AND/OR)을 지원하는 함수들을 제공한다.

1. Array와 Array의 비교 *-중요-*

In [36]:
import numpy as np

test_a = np.array([1,3,0], float) 
test_a

array([1., 3., 0.])

In [37]:
test_b = np.array([5,2,1], float) 
test_b

array([5., 2., 1.])

In [38]:
test_a > test_b

array([False,  True, False])

2. Array와 Scalar의 비교 *-중요-*
    - test_c라는 ndarray와 4라는 scalar 값을 비교하면 
        - scalar를 array로 brodacasting 한 뒤에,
        - element-wise operation이 일어난다.
    - 그렇기 때문에 0~3까지는 True가 나오고, 그 외에는 False가 담긴 array가 반환된다.

In [39]:
test_c = np.arange(10) 
test_c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
test_c < 4 # Broadcasting 되어 각 요소가 4보다 작은지 비교한 결과값의 배열을 return

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

3. np.logical_and와 np.logical_or
    - np.logical_and 함수는 각 element가 
        - 모든 조건을 충족할 경우 True, 
        - 하나라도 충족하지 못할 경우 False를 반환한다.
    - np.logical_or 함수는 반대로 
        - 하나라도 충족하면 True, 
        - 아닐 경우 False를 반환한다.


In [41]:
test_d = np.array([1,3,0], float)
test_d

array([1., 3., 0.])

In [42]:
np.logical_and(test_d > 0, test_d < 3) # 모든 조건을 충족할 경우 True, 아닐 경우 False

array([ True, False, False])

In [43]:
np.logical_or(test_d > 2, test_d < 1)

array([False,  True,  True])

4. np.where *-중요-*

In [44]:
np.where(test_d > 0) #test_d 배열 중 0보다 큰 값을 가진 요소들의 "index번호를 배열로 반환"하는 함수

(array([0, 1]),)

In [45]:
np.where(test_d > 0,3,2) # (condition, TRUE, FALSE)

array([3, 3, 2])

5. np.all과 np.any

In [46]:
np.all(test_c<5) # test_c<5의 모든 결과값이 True일 때만 True, 아니면 False

False

In [47]:
np.all(test_c<10) # test_c<10의 모든 결과값이 True이기 때문에 True

True

In [48]:
np.any(test_c>5)

True

In [49]:
np.any(test_c<0)

False

6. np.isnan, np.isfinite
    - NaN이란 Not a Number의 줄임말이다. 데이터를 입력하지 않은 경우 NaN으로 표기된다. 
    - Inf는 Divide By Zero 등을 통해 값이 이상해졌을 경우 np.Inf로 표기된다.
    - isnan 함수는 test_d 배열에서 NaN인 위치의 index를 반환하는 함수이다.
    - isfinite 함수는 각 위치의 값이 finite 한 값인지 infinite 한 값인지를 알려주는 함수이다.

In [50]:
test_d = np.array([1,np.NaN, np.Inf], float) 
test_d

array([ 1., nan, inf])

In [51]:
np.isnan(test_d)

array([False,  True, False])

In [52]:
np.isfinite(test_d)

array([ True, False, False])

- 마무리
    - Array 간의 비교, 논리 연산자는 항상 사용되는 함수들이다.
    - 다양한 기능들을 제공하는 만큼, 
        - 각각의 함수들이 
            - index를 반환하는지 
            - 실제 값을 반환하는지, 
            - array를 반환하는지 
            - Boolean을 반환하는지 정확하게 이해할 필요가 있다.

# **| *위치' 찾기* | 배열의 정렬**

Array sort/min/max 함수
- 배열의 값들을 오름차순/내림차순으로 정렬하는 방법을 알아보자.
- 그리고 배열의 최대 최소 값을 어떻게 추출할지, 
- 또 row/col 별 최대 최소값은 어떻게 추출할 수 있는지 알아보자.

1. argsort
    - a.argsort()는 a라는 ndarray를 오름차순 정렬하기 위한 index의 순서를 배열로 반환한다.
        - 즉, [2,1,0,3]은 오름차순 정렬하기 위해 a[2], a[1], a[0], a[3] 순서로 추출해야 된다는 것이다.
        - 위의 결과대로 추출할 경우 1,2,4,7이 순서대로 반환될 것이다.
    - 이를 확인하기 위해서 a[sort_index]로 fancy indexing을 하면 기대한 값이 나오는 것을 확인할 수 있다.
    - 내림차순으로 정렬하기 위해선, 위에서 추출한 sort_index를 뒤집어주면 된다.
        - 이 동작은 sort_index[::-1]을 하여 거꾸로 뽑을 수 있고, 
        - 뒤집힌 index를 가지고 fancy indexing을 수행하면 간단하게 내림차순 정렬이 가능하다.

In [53]:
import numpy as np
a = np.array([4,2,1,7])
a

array([4, 2, 1, 7])

In [57]:
sort_index = a.argsort() # 오름차순 기준 index 순서를 반환 
sort_index

array([2, 1, 0, 3])

In [58]:
a[sort_index] #fancy indexing으로 순서대로 추출

array([1, 2, 4, 7])

In [59]:
sort_index[::-1] # 기존의 순서를 거꾸로 추출한 결과 --> 내림차순

array([3, 0, 1, 2])

In [60]:
a[sort_index[::-1]] # a 배열로부터 내림차순 index로 fancy indexing

array([7, 4, 2, 1])

2. np.argmax
    - np.argmax(a)를 수행하면, 전체 a라는 배열 중 최대값이 있는 위치의 index를 알려준다.
        - 5라는 값은 1번 row의 1번 Col을 의미하기 때문에, 88이 max값이라는 것을 의미한다 

In [62]:
a = np.array([[4,2,4,7], [9,88,6,45], [9,76,3,0]]) 
a

array([[ 4,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  0]])

In [63]:
np.argmax(a) # 전체 배열 a 중의 max 값의 index

5

3. np.argmin
    -  np.argmin을 수행하면 
        - 0이라는 값을 가리키는 index 11이 나오게 된다.
    - 다른 말로, 2번 row에 3번 col에 위치한 "0을 찾기 위해"
        - 11이라는 값을 반환한 것이다.

In [64]:
np.argmin(a)

11

4. axis별 min/max 값 추출하기
    - 참고로, 대부분의 데이터에서는 전체 테이블의 최소/최대값을 찾는 것은 무의미하다.
        - 각 Col별 혹은 row별 최소/최대값을 찾기 위해서는 
            - "axis" parameter를 추가해줘야 한다.
    - 마찬가지로 각 row/col의 
        - 최소/최대값을 가진 요소의 index를 알려준다는 것을 이해해야 한다.

In [65]:
np.argmax(a, axis=1) # 결과값인 [3, 1, 1]은 각 row의 7, 88, 76이 최대값이라는 것을 의미한다.

array([3, 1, 1])

In [66]:
np.argmin(a, axis=0) # 결과값인 [0, 0, 2, 2]는 각 col의 4, 2, 3, 0이 최소값이라는 것을 의미한다.

array([0, 0, 2, 2])

마무리
- argsort, argmin, argmax 함수들은 
    - 직접 sorting을 해서 반환하는 것이 아니라, 
    - sorting 할 경우의 "index를 순서대로 반환"하는 함수이다.
- sorting/min/max 등의 index를 주기 때문에, 
    - 이 index를 가지고 
        - "Fancy indexing 하여 각각의 값을 확인"할 수 있다.

# **| *값' 찾기* | Boolean Index와 Fancy Index**

1. Boolean Index
    - test_a > 3이라고 하면 각 요소가 3보다 큰지에 대한 Boolean 값을 반환한다
        - 이 Boolean 배열을 test_a의 index로 전달하면, 
            - test_a 중 True인 index의 값들만 추출해서 보게 된다.
    - 이런 식으로 주어진 배열에서 조건을 충족하는 값들만 추출하는 방법을 Boolean indexing이라고 한다.

In [67]:
import numpy as np

test_a = np.array([1,4,0,2,3,8,9,7], float) 
test_a

array([1., 4., 0., 2., 3., 8., 9., 7.])

In [68]:
test_a > 3 # test_a 중에서 각 요소별로 3보다 큰지 작은지에 대한 boolean 값이 담김

array([False,  True, False, False, False,  True,  True,  True])

In [69]:
test_a[test_a > 3]

array([4., 8., 9., 7.])

2. Fancy Index
    - 우리가 일반적으로 test_b의 첫번째 값을 읽고 싶으면 test_b[0]라고 접근할 것이다.
        - 이러한 접근을 여러 개 한번에 하고 싶다면, 
            - index를 숫자 하나가 아니라 하나의 배열에 여러 숫자를 담아서 전달할 수 있다.
    - test_b를 접근하는 index를 cond라는 배열에 담아서 전달하니, 
        - test_b로 부터 각각의 index에 위치한 값들을 읽어낸다.
    - 만약, index 값이 너무 크다면? 
        - 당연히 index out of bounds error가 발생한다.

In [70]:
test_b = np.array([2,4,6,8], float)
test_b

array([2., 4., 6., 8.])

In [71]:
cond = np.array([1,1,1,2,1,0,1,3]) 
cond

array([1, 1, 1, 2, 1, 0, 1, 3])

In [72]:
test_b[cond] # test_b의 index를 접근할 때, cond 배열의 각각의 값으로 접근

array([4., 4., 4., 6., 4., 2., 4., 8.])

In [73]:
test_b.take(cond) # .take함수를 사용해서도 동일하게 fancy indexing을 할 수 있다.

array([4., 4., 4., 6., 4., 2., 4., 8.])

In [74]:
cond = np.array([4]) # 기존 test_b 배열의 max_index를 넘어가면 어떻게 될까? 
test_b[cond]

IndexError: index 4 is out of bounds for axis 0 with size 4

3. 2차원 이상 배열에서 Fancy indexing
    - cond_row의 값과 cond_col의 값을 각각 추출해서 순서대로 test_c로부터 추출하라는 명령어이다.
        - 결과는 
            ```
            test_c[0,0], 
            test_c[0,1], 
            test_c[1,1], 
            test_c[1,0], 
            test_c[0,1] 순서로 나오게 된다.
    - 조건은 cond_row와 cond_col의 shape가 동일해야 한다는 것이다.

In [75]:
test_c = np.array([[1,4], [9,16]], float) 
test_c

array([[ 1.,  4.],
       [ 9., 16.]])

In [76]:
cond_row = np.array([0,0,1,1,0]) 
cond_col = np.array([0,1,1,0,1])

In [77]:
test_c[cond_row, cond_col] 
# cond_row의 값과 cond_col의 값을 각각 추출해서 순서대로 test_c로부터 추출함

array([ 1.,  4., 16.,  9.,  4.])

# **텍스트 데이터를 읽기 저장하기** 

1. np.loadtxt와 np.savetxt 예시 (텍스트 데이터 읽기 / 저장하기)
    - np.loadtxt : 123 ~ 678이라는 값을 가진 populations.txt에서 tab으로 구분되어 있는 text 데이터를 읽어오는 함수이다.
        - delimiter란 데이터의 구분자가 tab이라는 것을 
            - numpy에게 알려주어 parsing을 위한 정보를 제공하는 것이다.
    - np.savetext를 통해서  동일한 데이터를 
        - format/delimiter를 지정하여 저장할 수 있다.
    - 결과는 컴퓨터에서 직접 실행하여 확인해야 한다. (int_data.csv파일 생성 여부 확인)

In [2]:
import numpy as np

a = np.loadtxt("./content.txt", delimiter='\t') 
a

ValueError: could not convert string ' ' to float64 at row 0, column 1.

In [ ]:
a_int = a.astype(int) 
a_int

In [ ]:
np.savetxt('int_data.csv', a_int, fmt='%.2e', delimiter=',')

2. NumPy object로 데이터 저장하고 읽기
    - np.save를 통해서 기존 array 데이터를 저장할 수 있다.
    - 이를 다시 불러오기 위해서는 np.load함수를 사용하면 된다

In [ ]:
np.save('npy_test', arr=a_int)

In [ ]:
a_test = np.load(file="npy_test.npy") 
a_test

In [ ]:
npy_array = np.load(file='npy_test.npy') 
npy_array

# **[ 출처 ]** : 티스토리, 개발자로 취업하기

https://coding-grandpa.tistory.com/m/category/Python%EA%B3%BC%20%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D/NumPy%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D