모두의 연구소, 2024 AI 코칭스터디 팀 활동을 통해 정리한 내용입니다.  
- 로롱코치_6팀 : @박문지 @서진형 @엄수빈 @엔터6(변찬우) @miji(박미지) @Shinar(신애라) 

# **Vector**

숫자를 원소로 가지는 list 또는 array

In [2]:
import numpy as np 

### **L1 노름 (맨해튼 노름)**
- L1 노름은 벡터의 각 성분의 절대값의 합으로 정의됩니다. 
- 이는 "맨해튼 거리"라고도 불리며, 다음과 같이 계산됩니다

In [4]:
# 예제 벡터
v = np.array([1, -2, 3])

# L1 노름 계산 = 벡터 요소의 절대값의 합으로 계산됩니다.
def l1_norm(x):
    x_norm = np.abs(x) # 1.각 절대값 구하기 
    x_norm = np.sum(x_norm) # 2.각각의 절대값 더하기 
    return x_norm

l1_norm = l1_norm(v)

print("벡터 v:", v)
print("L1 노름:", l1_norm)

벡터 v: [ 1 -2  3]
L1 노름: 6


### **L2 노름 (유클리드 노름)**
- L2 노름은 벡터의 각 성분의 제곱을 더한 후 제곱근을 취한 값으로 정의됩니다. 
- 이는 "유클리드 거리"라고도 불리며, 다음과 같이 계산됩니다:

In [6]:
# 예제 벡터
v = np.array([1, -2, 3])

# L2 노름 = 벡터 요소의 제곱을 더한 후 제곱근을 취한 값으로 계산됩니다.
# l2_norm = np.sqrt(np.sum(v ** 2))

def l2_norm(x):
    x_norm = x*x # 성분곱 연산 
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)# 제곱근 연산 
    return x_norm

l2_norm = l2_norm(v)

print("벡터 v:", v)
print("L2 노름:", l2_norm)

벡터 v: [ 1 -2  3]
L2 노름: 3.7416573867739413


### **두 벡터 사이의 거리 구하기**

In [7]:
import numpy as np

# 두 벡터 정의
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("벡터 a:", a)
print("벡터 b:", b)

# 기본 함수 사용 
l1_distance = np.sum(np.abs(a - b)) # L1 거리 계산
l2_distance = np.sqrt(np.sum((a - b) ** 2)) # L2 거리 계산
print("L1 거리:", l1_distance)
print("L2 거리:", l2_distance)

# 내장 함수(선형 대수) 사용
l1_distance_builtin = np.linalg.norm(a - b, ord=1) # ord=1: L1 노름
l2_distance_builtin = np.linalg.norm(a - b, ord=2) # ord=2: L2 노름 

print("L1 거리 (내장 함수):", l1_distance_builtin)
print("L2 거리 (내장 함수):", l2_distance_builtin)


벡터 a: [1 2 3]
벡터 b: [4 5 6]
L1 거리: 9
L2 거리: 5.196152422706632
L1 거리 (내장 함수): 9.0
L2 거리 (내장 함수): 5.196152422706632


## **내적** 

### 두 벡터 사이의 각도 구하기

In [10]:
# 두 벡터를 정의
vector1 = np.array([3, 4]) 
vector2 = np.array([1, 2]) 

def calculate_angle_between_vectors(vector1, vector2):
    # 벡터의 내적 계산
    dot_product = np.dot(vector1, vector2)
    
    # 각 벡터의 크기 계산
    magnitude1 = np.linalg.norm(vector1)
    magnitude2 = np.linalg.norm(vector2)
    
    # 벡터 사이의 각도 계산
    cos_theta = dot_product / (magnitude1 * magnitude2)
    angle_in_radians = np.arccos(cos_theta)
    
    # 라디안 값을 도 단위로 변환
    angle_in_degrees = np.degrees(angle_in_radians)
    
    return angle_in_degrees


# 두 벡터 사이의 각도 계산
angle = calculate_angle_between_vectors(vector1, vector2)
print("두 벡터 사이의 각도는 {}도입니다.".format(angle))


np.inner(vector1,vector2)
np.dot(vector1,vector2)
print("case - inner : {} 도".format(angle))
print("case - dot :  {} 도".format(angle))
print("case - @ : ", vector1*vector2)


두 벡터 사이의 각도는 10.304846468766044도입니다.
case - inner : 10.304846468766044 도
case - dot :  10.304846468766044 도
case - @ :  [3 8]


### 벡터와 벡터의 곱하기 

In [11]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

dot_product = np.dot(vector1, vector2)
print("두 벡터의 내적:", dot_product) # 내적 값은 클 수록 두 벡터가 유사한 방향을 갖음


두 벡터의 내적: 32


### 벡터간의 유사도 계산

In [13]:
import numpy as np

# 두 벡터를 예시로 사용
vector1 = np.array([0.2, 0.4, 0.5])
vector2 = np.array([0.1, 0.3, 0.7])

# 두 벡터의 곱 계산
dot_product = np.dot(vector1, vector2)

# 각 벡터의 크기 계산
magnitude1 = np.linalg.norm(vector1)
magnitude2 = np.linalg.norm(vector2)

# 유사도를 측정(완전 일치는 1, 완전 불일치는 0)
similarity = dot_product / (magnitude1 * magnitude2)
print("두 벡터의 유사도:", similarity) 


두 벡터의 유사도: 0.9509634325746504


# **Matrix**

벡터를 원소로 가지는 2차원 배열 
- 행렬은 행(row)과 열(column)이라는 인덱스(index)를 가진다 
- 행렬의 행(row)과 열(column)의 인덱스를 바꿔 전치행렬 transpose matrix로 변환할 수 있다 

**행렬의 덧셈 (Matrix Addition)**
- 두 행렬을 더하려면 각 행렬의 동일한 위치에 있는 요소들을 더합니다. 
- 두 행렬의 크기가 동일해야 합니다.

In [2]:
# 두 행렬 정의
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 행렬 덧셈
C = A + B

print("행렬 A:")
print(A)
print("\n행렬 B:")
print(B)
print("\n행렬 A + B:")
print(C)

행렬 A:
[[1 2]
 [3 4]]

행렬 B:
[[5 6]
 [7 8]]

행렬 A + B:
[[ 6  8]
 [10 12]]


**행렬의 뺄셈 (Matrix Subtraction)**
- 두 행렬을 빼려면 각 행렬의 동일한 위치에 있는 요소들을 뺍니다. 
- 두 행렬의 크기가 동일해야 합니다.

In [5]:
# 행렬 뺄셈
C = A - B

print("행렬 A:")
print(A)
print("\n행렬 B:")
print(B)
print("\n행렬 A - B:")
print(C)

행렬 A:
[[1 2]
 [3 4]]

행렬 B:
[[5 6]
 [7 8]]

행렬 A - B:
[[-4 -4]
 [-4 -4]]


**스칼라곱 (Scalar Multiplication)**
- 행렬의 각 요소에 스칼라 값을 곱합니다.

In [4]:
# 스칼라 정의
scalar = 2

# 스칼라곱
C = A * scalar

print("행렬 A:")
print(A)
print("\n스칼라 값:")
print(scalar)
print("\n행렬 A * 스칼라:")
print(C)

행렬 A:
[[1 2]
 [3 4]]

스칼라 값:
2

행렬 A * 스칼라:
[[2 4]
 [6 8]]


**전치행렬(transpose matrix)A_T = np.transpose(A)**
- 주어진 행렬의 행과 열을 교환하여 얻은 행렬입니다. 
- 전치행렬은 원래 행렬 𝐴의 행(row)을 열(column)로, 열을 행으로 바꾸어 생성됩니다. 

- 전치행렬의 주요 속성:
    - A(A^T)^T : 전치행렬의 전치행렬은 원래 행렬과 같습니다.
    - (A + B)^T = A^T + B^T: 두 행렬의 합의 전치는 각각의 전치행렬의 합과 같습니다.
    - (cA)^T = cA^T: 상수 c를 곱한 행렬의 전치는 상수 c와 전치행렬을 곱한 것과 같습니다.
    - (AB)^T = B^T A^T: 두 행렬의 곱의 전치는 각각의 전치행렬을 순서를 바꾸어 곱한 것과 같습니다.

In [6]:
# 행렬 정의
A = np.array([[1, 2, 3], [4, 5, 6]])

print("행렬 A:")
print(A)

# 전치행렬 계산
A_T = np.transpose(A)
# 또는 A_T = A.T를 사용할 수 있습니다

print("\n행렬 A의 전치행렬:")
print(A_T)

행렬 A:
[[1 2 3]
 [4 5 6]]

행렬 A의 전치행렬:
[[1 4]
 [2 5]
 [3 6]]


### **행렬의 곱셈 C = 'np.dot(A, B)' 또는 'A @ B'**
- 𝑖 번째 행벡터와 𝑗 번째 열벡터 사이의 **내적을 성분**으로 가지는 행렬을 계산
- 두 행렬의 곱을 계산하는 방법으로, 두 행렬 𝐴와 𝐵의 곱 𝐶 = 𝐴𝐵는 다음과 같은 규칙에 따라 계산됩니다: 
    - 𝐴의 **열**의 수와 𝐵의 **행**의 수가 같아야 합니다. 
        - 즉, 𝐴가 𝑚 × 𝑛 행렬이고 𝐵가 𝑛 × 𝑝 행렬일 때, 𝐶 는 𝑚 × 𝑝 행렬이 됩니다. 
        - 𝐶 의 각 요소 𝑐 𝑖 𝑗 ​는 𝐴의 𝑖 번째 행과 𝐵의 𝑗 번째 열의 각 요소를 곱한 후 모두 더한 값입니다.

### 2x2 행렬x행렬의 내적(곱셈)

In [7]:
# 2x2 행렬의 곱셈
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 행렬 곱셈
C = np.dot(A, B)
# 또는 C = A @ B 를 사용할 수 있습니다

print("행렬 A:")
print(A)
print("\n행렬 B:")
print(B)
print("\n행렬 A와 B의 곱 (AB):")
print(C)

행렬 A:
[[1 2]
 [3 4]]

행렬 B:
[[5 6]
 [7 8]]

행렬 A와 B의 곱 (AB):
[[19 22]
 [43 50]]


### 2x3와 3x2 행렬x행렬의 내적(곱셈)

In [8]:
# 2x3와 3x2 행렬의 곱셈
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

# 행렬 곱셈
C = np.dot(A, B)
# 또는 C = A @ B 를 사용할 수 있습니다

print("행렬 A:")
print(A)
print("\n행렬 B:")
print(B)
print("\n행렬 A와 B의 곱 (AB):")
print(C)

행렬 A:
[[1 2 3]
 [4 5 6]]

행렬 B:
[[ 7  8]
 [ 9 10]
 [11 12]]

행렬 A와 B의 곱 (AB):
[[ 58  64]
 [139 154]]


### 3x2와 2x3 행렬x행렬의 내적(곱셈)

In [9]:
# 3x2와 2x3 행렬의 곱셈
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

# 행렬 곱셈
C = np.dot(A, B)
# 또는 C = A @ B 를 사용할 수 있습니다

print("행렬 A:")
print(A)
print("\n행렬 B:")
print(B)
print("\n행렬 A와 B의 곱 (AB):")
print(C)


행렬 A:
[[1 2]
 [3 4]
 [5 6]]

행렬 B:
[[ 7  8  9]
 [10 11 12]]

행렬 A와 B의 곱 (AB):
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


### **행렬과 벡터의 내적**
- 행렬 𝐴와 벡터 𝑏의 내적은 행렬의 각 행과 벡터의 내적을 계산하여 새로운 벡터를 만듭니다.

In [11]:
# 행렬 A와 벡터 b 정의
A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8, 9])

# 행렬과 벡터의 내적
result = np.dot(A, b)
# 또는 result = A @ b 를 사용할 수 있습니다

print("행렬 A:")
print(A)
print("벡터 b:", b)
print("행렬 A와 벡터 b의 내적:")
print(result)


행렬 A:
[[1 2 3]
 [4 5 6]]
벡터 b: [7 8 9]
행렬 A와 벡터 b의 내적:
[ 50 122]


### **역행렬**
- 선형 방정식을 푸는 데 유용한 수학적 도구입니다.
- 역행렬은 정방 행렬에만 정의됩니다
- 역행렬은 주어진 정방 행렬 𝐴에 대해 다음을 만족하는 행렬 𝐵입니다.
    - A⋅B=B⋅A=I
- 여기서 𝐼는 항등 행렬입니다. 즉, 𝐴와 𝐵를 곱했을 때 항등 행렬이 되어야 합니다.

1. NumPy를 사용한 역행렬 계산 예시:

In [16]:
import numpy as np

# 역행렬을 계산할 행렬 A를 정의합니다. (예시로 임의의 값 사용)
A = np.array([[1, 2], [3, 4]])

# NumPy의 inv 함수를 사용하여 역행렬을 계산합니다.
A_inv = np.linalg.inv(A)

print("행렬 A:\n", A)
print("\n행렬 A의 역행렬:\n", A_inv)


행렬 A:
 [[1 2]
 [3 4]]

행렬 A의 역행렬:
 [[-2.   1. ]
 [ 1.5 -0.5]]


2. SciPy를 사용한 역행렬 계산 예시:

In [20]:
from scipy.linalg import inv

# 역행렬을 계산할 행렬 A를 정의합니다. (예시로 임의의 값 사용)
A = np.array([[1, 2], [3, 4]])

# SciPy의 inv 함수를 사용하여 역행렬을 계산합니다.
A_inv = inv(A)

print("행렬 A:\n", A)
print("\n행렬 A의 역행렬:\n", A_inv)

행렬 A:
 [[1 2]
 [3 4]]

행렬 A의 역행렬:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### **유사 역행렬**
- 역행렬과 달리, 
    - 유사역행렬은 정방 행렬이 아니거나 역행렬이 존재하지 않는 행렬에 대해서도 정의될 수 있습니다.
- 유사 역행렬은 **𝐴의 의사 역행렬** 또는 **무어-펜로즈 역행렬**이라고도 합니다.

In [22]:
# 유사역행렬을 계산할 행렬 A를 정의합니다. (예시로 임의의 값 사용)
A = np.array([[1, 2], [3, 4], [5, 6]])

# NumPy의 pinv 함수를 사용하여 유사역행렬을 계산합니다.
A_pseudo_inv = np.linalg.pinv(A)

print("행렬 A:\n", A)
print("\n행렬 A의 유사역행렬:\n", A_pseudo_inv)

행렬 A:
 [[1 2]
 [3 4]
 [5 6]]

행렬 A의 유사역행렬:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


### **선형회귀분석**
- 선형 회귀 분석은 주어진 데이터에 대해 **선형 관계를 나타내는 모델을 만들고**, 
- 이 모델을 사용하여 **종속 변수와 독립 변수 간의 관계를 예측**하는 것을 목표로 합니다. 
    - 이를 위해 최소 제곱법(Least Squares Method)을 사용하여 모델의 계수를 "추정"합니다. 
    - 역행렬 또는 유사 역행렬을 사용하여 이러한 계수를 "계산"할 수 있습니다.

In [23]:
X = np.array([[1, 2], [3, 4], [5, 6]])  
y = np.array([3, 4, 5]) 

X_transpose = np.transpose(X)  
X_transpose_X_inv = np.linalg.inv(np.dot(X_transpose, X)) 
coefficients = np.dot(np.dot(X_transpose_X_inv, X_transpose), y)  

print("회귀 모델의 계수:", coefficients)


회귀 모델의 계수: [-2.   2.5]


In [25]:
# 예시 데이터 생성
X = np.array([[1, 2], [3, 4], [5, 6]])  # 독립 변수 행렬
y = np.array([3, 4, 5])  # 종속 변수 벡터

# 선형 회귀 모델의 계수를 추정하는 함수
def estimate_coefficients(X, y):
    X_transpose = np.transpose(X)  # X의 전치 행렬
    dot_product = np.dot(X_transpose, X)  # 벡터의 내적 계산
    X_transpose_X_inv = np.linalg.inv(dot_product) # 각 벡터의 크기 계산
    coefficients = np.dot(np.dot(X_transpose_X_inv, X_transpose), y) # 회귀 모델의 계수 벡터
    
    return coefficients

# 선형 회귀 모델의 계수 추정
coefficients = estimate_coefficients(X, y)
print("회귀 모델의 계수:", coefficients)


회귀 모델의 계수: [-2.   2.5]
